### ISSUE TITLE
share the predicted SQL file

### ISSUE THREAD

**Issue by linxin6** [LUMIA-Group/rasat#18]
Hello, may I ask if you can share the predicted SQL that you finally ran on the validation set? Replicating your work is too time-consuming for me as my server does not have a GPU.
![image](https://github.com/LUMIA-Group/rasat/assets/122243370/0da64b49-f150-43ed-ab75-0dc41444ac97)

**Comment by JiexingQi** [comment]
Sorry, I cannot find it. This is not normal because when I submitted my experiment checkpoint on Codalab, which also only uses GPU, it consumed less than 10 hours, not 656 hours.
The codalab sheet record it: https://worksheets.codalab.org/bundles/0xea7718b26e884d268ebf884aa92a4f89
The prediction SQL can be found in this codalab project too: https://worksheets.codalab.org/worksheets/0x58a9773343bc45c19298feef618b4a8a

**Comment by JiexingQi** [comment]
@linxin6

**Comment by linxin6** [comment]
Thank you for your reply. I have successfully obtained the predicted SQL now.
